server:
  port: 8080
spring:
  application:
    name: todo
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;
    username: sumit
    password: p
  h2:
    console:
      enabled: true
      path: /h2-ui
  jpa:
      defer-datasource-initialization: true
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          default-schema: TODO_DATA
          dialect: org.hibernate.dialect.H2Dialect
      show-sql: true
      
springdoc:
  swagger-ui:
    path: /documentation  # Configures the URL path for the Swagger UI
  api-docs:
    enabled: true         # Enables or disables the API documentation endpoint
    path: /api-docs  

